### ISSUE TITLE
[Question] - iOS timeline

### ISSUE THREAD

**Issue by angel1st** [rodrigowerberich/barcode_platform_view#1]
Any plans for iOS support? The plugin seems quite promising, however, iOS support along with Android is mandatory for my app.
Thanks for the good work so far :-)

**Comment by rodrigowerberich** [comment]
@angel1st, iOS support is also mandatory on my app. But this week I'm having to deal with some other pressing issues. I estimate iOS support by the end of the next week.

**Comment by rodrigowerberich** [comment]
Just pushed a working, but not so polished ios working version, but we found another more advanced working plugin to use, so we will suspend support to this one for now. 

This is the link to the package we found https://pub.dev/packages/qr_code_scanner
